#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and on the 9th prints HI
while [[ $i -lt 10 ]]
do
    if [ $i -eq 9 ]
    then
	 echo "Hi"
    fi
    echo "Best School"
    ((i = i + 1))
done
