#!/usr/bin/env bash
# This script is displaying the counter number 20 times with cases

counter=0
minutes=1

while [ $counter -le 12 ]
do
	echo "Hour: ${counter}"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		((minutes++))
	done
	minutes=1
	((counter++))
done
